// src/components/Layouts/zone-overrides.ts
// ─────────────────────────────────────────────────────────────────────────────
// Zone layout registry — managed by the unt.ink TUI.
//
// DO NOT edit this file manually. Use the TUI zone wizard to add zones
// and the TUI zone delete action to remove them.
//
// Each entry maps a NEXT_PUBLIC_ZONE key to its layout configuration.
// routeClassifier.ts imports this at module scope. Because NEXT_PUBLIC_ZONE
// is baked at Docker build time, the lookup is effectively a build-time branch
// — only the matching zone's entry is ever evaluated at runtime.
//
// Scaffold adds:    key: { layoutType: "...", appFooter: "..." },
// Delete removes:   the line for that key.
// ─────────────────────────────────────────────────────────────────────────────

export type ZoneLayoutConfig = {
  /** Layout shell this zone uses — determines header/footer in ClientLayout. */
  layoutType: "landing" | "shop" | "app" | "minimal";
  /** Footer variant rendered inside AppLayout. Only used when layoutType="app". */
  appFooter:  "none" | "shop" | "landing";
};

export const ZONE_LAYOUTS: Record<string, ZoneLayoutConfig> = {
  blog:     { layoutType: "landing", appFooter: "none" },
  shop:     { layoutType: "shop",    appFooter: "none" },
  apptest1: { layoutType: "app",     appFooter: "none" },
  min:      { layoutType: "minimal", appFooter: "none" },
  yayy:     { layoutType: "landing", appFooter: "none" },
  running:  { layoutType: "minimal", appFooter: "none" },
  rappers:  { layoutType: "minimal", appFooter: "none" },
  onemore:  { layoutType: "app", appFooter: "none" },
  logs:     { layoutType: "minimal", appFooter: "none" },
  logz:     { layoutType: "minimal", appFooter: "none" },
};
