import type {
  ChatMessage,
  TankCamera,
  TankChannel,
  TankRoom,
} from "./contracts";

// Static identity/metadata only — name, location, description, tags. Live
// health, bitrate, latency, and presence come from the receiver-manager
// snapshot (src/zones/tank/server/receiverManager.ts, served at
// /api/tank/cameras) and are merged in client-side. Nothing in this file
// should ever claim a camera is live; that's why health/bitrate/viewers
// below are all zeroed — nobody reads them for live state anymore.
//
// IMPORTANT: `id` must exactly match the camera id configured in the SRT
// receiver app (USB/ethernet SRT, SRTLA, or mobile/IRL Pro ingest) for the
// live overlay to link up automatically. If the real provisioned id ends up
// different, rename it here to match — that's the only place it's defined.
export const cameras: TankCamera[] = [
  {
    id: "cam-1786768240090",
    slug: "cam0",
    name: "Game Room",
    location: "Game room",
    description: "The fixed IP camera on the game room.",
    health: "offline",
    bitrateKbps: 0,
    latencyMs: null,
    viewers: 0,
    priority: 1,
    enabled: true,
    isPublic: true,
    delivery: "coming-soon",
    accent: "from-slate-700/60 via-slate-900/70 to-black",
  },
  {
    id: "cam-1786768240091",
    slug: "cam1",
    name: "Living Room",
    location: "Living room",
    description: "The fixed IP camera on the living room.",
    health: "offline",
    bitrateKbps: 0,
    latencyMs: null,
    viewers: 0,
    priority: 2,
    enabled: true,
    isPublic: true,
    delivery: "coming-soon",
    accent: "from-slate-700/60 via-slate-900/70 to-black",
  },
  {
    id: "cam-1786768240092",
    slug: "cam2",
    name: "Kitchen",
    location: "Kitchen",
    description: "The fixed IP camera on the kitchen.",
    health: "offline",
    bitrateKbps: 0,
    latencyMs: null,
    viewers: 0,
    priority: 3,
    enabled: true,
    isPublic: true,
    delivery: "coming-soon",
    accent: "from-slate-700/60 via-slate-900/70 to-black",
  },
  {
    id: "cam-1786768240093",
    slug: "cam3",
    name: "The Foyer",
    location: "The Foyer",
    description: "The fixed IP camera on the foyer.",
    health: "offline",
    bitrateKbps: 0,
    latencyMs: null,
    viewers: 0,
    priority: 4,
    enabled: true,
    isPublic: true,
    delivery: "coming-soon",
    accent: "from-slate-700/60 via-slate-900/70 to-black",
  },
  {
    id: "cam-1786768240094",
    slug: "cam4",
    name: "Makeup Room",
    location: "Makeup room",
    description: "The fixed IP camera on the makeup room.",
    health: "offline",
    bitrateKbps: 0,
    latencyMs: null,
    viewers: 0,
    priority: 5,
    enabled: true,
    isPublic: true,
    delivery: "coming-soon",
    accent: "from-slate-700/60 via-slate-900/70 to-black",
  },
  {
    id: "cam-1786768240095",
    slug: "cam5",
    name: "Game Room 2",
    location: "Game Room 2",
    description: "The fixed IP camera on game room 2.",
    health: "offline",
    bitrateKbps: 0,
    latencyMs: null,
    viewers: 0,
    priority: 6,
    enabled: true,
    isPublic: true,
    delivery: "coming-soon",
    accent: "from-slate-700/60 via-slate-900/70 to-black",
  },
  {
    id: "remote-cam-1",
    slug: "remote-cam-1",
    name: "Remote Camera 1",
    location: "Roaming",
    description: "Mobile roaming camera.",
    health: "offline",
    bitrateKbps: 0,
    latencyMs: null,
    viewers: 0,
    priority: 7,
    enabled: true,
    isPublic: true,
    delivery: "coming-soon",
    accent: "from-slate-700/60 via-slate-900/70 to-black",
  },
];

export const channels: TankChannel[] = [
  {
    id: "channel-director",
    slug: "director",
    name: "Tank Director",
    handle: "@tankdirector",
    bio: "The continuous program feed, cut live from every connected house camera.",
    verified: true,
    followers: 0,
    live: false,
    category: "IRL",
    cameraIds: [
      "cam-1786768240090",
      "cam-1786768240091",
      "cam-1786768240092",
      "cam-1786768240093",
      "cam-1786768240094",
      "cam-1786768240095",
    ],
  },
  {
    id: "channel-game-room",
    slug: "game-room",
    name: "Game Room",
    handle: "@gameroom",
    bio: "The game room camera feed.",
    verified: false,
    followers: 0,
    live: false,
    category: "IRL",
    cameraIds: ["cam-1786768240090"],
  },
  {
    id: "channel-living-room",
    slug: "living-room",
    name: "Living Room",
    handle: "@livingroom",
    bio: "The living room camera feed.",
    verified: false,
    followers: 0,
    live: false,
    category: "IRL",
    cameraIds: ["cam-1786768240091"],
  },
  {
    id: "channel-kitchen",
    slug: "kitchen",
    name: "Kitchen",
    handle: "@kitchen",
    bio: "The kitchen camera feed.",
    verified: false,
    followers: 0,
    live: false,
    category: "IRL",
    cameraIds: ["cam-1786768240092"],
  },
  {
    id: "channel-foyer",
    slug: "foyer",
    name: "The Foyer",
    handle: "@foyer",
    bio: "The foyer camera feed.",
    verified: false,
    followers: 0,
    live: false,
    category: "IRL",
    cameraIds: ["cam-1786768240093"],
  },
  {
    id: "channel-makeup-room",
    slug: "makeup-room",
    name: "Makeup Room",
    handle: "@makeuproom",
    bio: "The makeup room camera feed.",
    verified: false,
    followers: 0,
    live: false,
    category: "IRL",
    cameraIds: ["cam-1786768240094"],
  },
  {
    id: "channel-game-room-2",
    slug: "game-room-2",
    name: "Game Room 2",
    handle: "@gameroom2",
    bio: "The game room 2 camera feed.",
    verified: false,
    followers: 0,
    live: false,
    category: "IRL",
    cameraIds: ["cam-1786768240095"],
  },
];

export const rooms: TankRoom[] = [
  {
    id: "room-program",
    slug: "director",
    title: "Director Live",
    eyebrow: "Main program",
    description:
      "One continuously directed feed, switching across every connected house camera as it comes online.",
    channelId: "channel-director",
    cameraIds: [
      "cam-1786768240090",
      "cam-1786768240091",
      "cam-1786768240092",
      "cam-1786768240093",
      "cam-1786768240094",
      "cam-1786768240095",
    ],
    featuredCameraId: "cam-1786768240090",
    live: false,
    viewers: 0,
    tags: ["Live", "Multi-camera"],
  },
  {
    id: "room-game-room",
    slug: "game-room",
    title: "Game Room",
    eyebrow: "First room",
    description: "The game room camera feed.",
    channelId: "channel-game-room",
    cameraIds: ["cam-1786768240090"],
    featuredCameraId: "cam-1786768240090",
    live: false,
    viewers: 0,
    tags: ["Game room", "IRL"],
  },
  {
    id: "room-living-room",
    slug: "living-room",
    title: "Living Room",
    eyebrow: "Second room",
    description: "The living room camera feed.",
    channelId: "channel-living-room",
    cameraIds: ["cam-1786768240091"],
    featuredCameraId: "cam-1786768240091",
    live: false,
    viewers: 0,
    tags: ["Living room", "IRL"],
  },
  {
    id: "room-kitchen",
    slug: "kitchen",
    title: "Kitchen",
    eyebrow: "Third room",
    description: "The kitchen camera feed.",
    channelId: "channel-kitchen",
    cameraIds: ["cam-1786768240092"],
    featuredCameraId: "cam-1786768240092",
    live: false,
    viewers: 0,
    tags: ["Kitchen", "IRL"],
  },
  {
    id: "room-foyer",
    slug: "foyer",
    title: "The Foyer",
    eyebrow: "Fourth room",
    description: "The foyer camera feed.",
    channelId: "channel-foyer",
    cameraIds: ["cam-1786768240093"],
    featuredCameraId: "cam-1786768240093",
    live: false,
    viewers: 0,
    tags: ["The Foyer", "IRL"],
  },
  {
    id: "room-makeup-room",
    slug: "makeup-room",
    title: "Makeup Room",
    eyebrow: "Fifth room",
    description: "The makeup room camera feed.",
    channelId: "channel-makeup-room",
    cameraIds: ["cam-1786768240094"],
    featuredCameraId: "cam-1786768240094",
    live: false,
    viewers: 0,
    tags: ["Makeup Room", "IRL"],
  },
  {
    id: "room-game-room-2",
    slug: "game-room-2",
    title: "Game Room 2",
    eyebrow: "Sixth room",
    description: "The game room 2 camera feed.",
    channelId: "channel-game-room-2",
    cameraIds: ["cam-1786768240095"],
    featuredCameraId: "cam-1786768240095",
    live: false,
    viewers: 0,
    tags: ["Game Room 2", "IRL"],
  },
];

// No seeded demo chat — real messages come from Supabase Realtime via
// useTankRealtimeChat as soon as someone posts.
export const chatMessages: ChatMessage[] = [];

export function cameraById(id: string) {
  return cameras.find((camera) => camera.id === id);
}
export function roomBySlug(slug: string) {
  return rooms.find((room) => room.slug === slug);
}
export function channelBySlug(slug: string) {
  return channels.find((channel) => channel.slug === slug);
}
