-- Tank's public connecting-loop bucket also stores recent social-card stills.
-- Keep the existing MP4 allowlist and add only the JPEG format generated by
-- MediaMTX; real archive footage remains in the separate private bucket.
update storage.buckets
set allowed_mime_types = case
  when allowed_mime_types is null then null
  when not ('image/jpeg' = any(allowed_mime_types))
    then array_append(allowed_mime_types, 'image/jpeg')
  else allowed_mime_types
end
where id = 'tank-loops';
