// src/ink/zone/docker-compose.ts
// @deprecated Root docker-compose.yml patching. Legacy path only.
//
// New zones use per-zone compose files (zones/<key>/docker-compose.yml)
// generated by genZoneCompose() in zone-templates.ts. The root compose is
// never touched for new-style zones.
//
// This file is kept for backwards compatibility with old zones whose service
// blocks still live in the root docker-compose.yml. Do not add new callers.

import { existsSync } from "fs";
import { join } from "path";
import { YAMLMap, YAMLSeq } from "yaml";
import { PROJECT_DIR } from "../../config/stack.ts";
import { readCompose, writeCompose, removeService } from "./compose-utils.ts";
import type { OnLine } from "./types.ts";

export async function removeFromDockerCompose(key: string, onLine: OnLine): Promise<void> {
  const composePath = join(PROJECT_DIR, "docker-compose.yml");
  if (!existsSync(composePath)) {
    onLine("  docker-compose.yml not found - skipping");
    return;
  }

  const doc = readCompose(composePath);

  const removed = removeService(doc, key);
  if (removed) {
    onLine(`  Removed service block "${key}" from docker-compose.yml`);
  } else {
    onLine(`  Service block for "${key}" not found in docker-compose.yml - skipping`);
  }

  const proxy = getService(doc, "proxy");
  let extraChanged = false;

  const upstreamKey = `UPSTREAM_${key.toUpperCase()}`;
  if (proxy && removeEnvironmentKey(proxy, upstreamKey)) {
    onLine(`  Removed ${upstreamKey} from proxy environment`);
    extraChanged = true;
  }

  if (proxy && removeDependsOnKey(proxy, key)) {
    onLine(`  Removed "${key}" from proxy depends_on`);
    extraChanged = true;
  }

  if (removed || extraChanged) {
    await writeCompose(composePath, doc);
  }
}

function getService(doc: ReturnType<typeof readCompose>, serviceName: string): YAMLMap | null {
  const services = doc.get("services");
  if (!(services instanceof YAMLMap)) return null;

  const service = services.get(serviceName);
  return service instanceof YAMLMap ? service : null;
}

function nodeText(node: unknown): string {
  if (typeof node === "string") return node;
  if (node && typeof node === "object" && "value" in node) {
    return String((node as { value: unknown }).value ?? "");
  }
  return "";
}

function removeEnvironmentKey(service: YAMLMap, key: string): boolean {
  const env = service.get("environment");
  if (env instanceof YAMLMap) {
    if (!env.has(key)) return false;
    env.delete(key);
    return true;
  }

  if (env instanceof YAMLSeq) {
    const before = env.items.length;
    env.items = env.items.filter((item) => {
      const text = nodeText(item);
      return text !== key && !text.startsWith(`${key}=`);
    });
    return env.items.length !== before;
  }

  return false;
}

function removeDependsOnKey(service: YAMLMap, key: string): boolean {
  const dependsOn = service.get("depends_on");
  if (dependsOn instanceof YAMLMap) {
    if (!dependsOn.has(key)) return false;
    dependsOn.delete(key);
    return true;
  }

  if (dependsOn instanceof YAMLSeq) {
    const before = dependsOn.items.length;
    dependsOn.items = dependsOn.items.filter((item) => nodeText(item) !== key);
    return dependsOn.items.length !== before;
  }

  return false;
}
