// src/ink/zone/docker-compose.ts
// ─────────────────────────────────────────────────────────────────────────────
// @deprecated  Root docker-compose.yml patching — legacy path only.
//
// New zones use per-zone compose files (zones/<key>/docker-compose.yml)
// generated by genZoneCompose() in zone-templates.ts.  The root compose
// is never touched for new-style zones.
//
// This file is kept for backwards-compat with old zones whose service blocks
// still live in the root docker-compose.yml.  Do NOT add new callers.
// Once all old zones are migrated, this file can be deleted along with its
// exports from zone/index.ts.
// ─────────────────────────────────────────────────────────────────────────────

import { join } from "path";
import { existsSync, readFileSync } from "fs";
import { PROJECT_DIR } from "../../config/stack.ts";
import { writeFileAtomic } from "../../utils/zoneScaffolding.ts";
import type { DerivedZone, OnLine } from "./types.ts";

// ── Generate docker-compose service block ─────────────────────────────────────

export function genComposeService(z: DerivedZone): string {
  return `
  ${z.service}:
    # image: the GHCR-published tag this zone builds to.  Without this line,
    # 'docker compose pull' is a no-op ("Skipped No image to be pulled") and
    # 'docker compose up' falls back to '{project}-{service}:latest' (e.g.
    # 'webbymk2-${z.key}:latest') which is NOT what our TUI build produces —
    # the TUI tags builds as ${z.image}.  Missing this line was the exact
    # cause of "No such image: webbymk2-${z.key}:latest" on first deploy.
    image: ${z.image}
    build:
      context: .
      dockerfile: zones/${z.key}/Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL:
        NEXT_PUBLIC_SUPABASE_URL_BROWSER:
        NEXT_PUBLIC_SUPABASE_ANON_KEY:
        NEXT_PUBLIC_APP_TITLE:
        NEXT_PUBLIC_COMPANY_NAME:
        NEXT_PUBLIC_OWNER_USERNAME:
        NEXT_PUBLIC_OWNER_EMAIL:
    container_name: ${z.container}
    restart: unless-stopped
    env_file: .env
    environment:
      NEXT_PUBLIC_ZONE: "${z.key}"
    healthcheck:
      test: ["CMD-SHELL", "node -e \\"require('http').get('http://localhost:3000/',r=>process.exit(r.statusCode<500?0:1)).on('error',()=>process.exit(1))\\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    depends_on:
      db:
        condition: service_healthy
      kong:
        condition: service_started
    networks:
      - unenter
`;
}

// ── Patch docker-compose.yml with zone service ────────────────────────────────

export async function patchDockerCompose(z: DerivedZone, onLine: OnLine): Promise<void> {
  const composePath = join(PROJECT_DIR, "docker-compose.yml");

  if (!existsSync(composePath)) {
    onLine(`�a� docker-compose.yml not found — skipping`);
    return;
  }

  let content = readFileSync(composePath, "utf-8");

  // Guard: already patched
  if (content.includes(`container_name: ${z.container}`)) {
    onLine(`�a� docker-compose.yml already has service for "${z.key}" — skipping`);
    return;
  }

  // Add service block — append after the last zone service.
  // We look for the last "      - unenter" line (each service's network attachment)
  // and insert after it.  This avoids hitting the top-level `networks:` definition
  // which appears at the TOP of the file (before `services:`), not the bottom.
  const networkAttach = "      - unenter";
  const attachIdx = content.lastIndexOf(networkAttach);
  if (attachIdx === -1) {
    // Fallback: just append at the very end
    content = content.trimEnd() + "\n" + genComposeService(z);
    onLine(`� Added compose service "${z.service}" (appended)`);
  } else {
    const insertAfter = attachIdx + networkAttach.length;
    content =
      content.slice(0, insertAfter) +
      genComposeService(z) +
      content.slice(insertAfter);
    onLine(`� Added compose service "${z.service}"`);
  }

  await writeFileAtomic(composePath, content);
}

// ── Remove zone from docker-compose.yml ───────────────────────────────────────

export async function removeFromDockerCompose(key: string, onLine: OnLine): Promise<void> {
  const composePath = join(PROJECT_DIR, "docker-compose.yml");
  if (!existsSync(composePath)) { onLine(`�a� docker-compose.yml not found — skipping`); return; }

  let content = readFileSync(composePath, "utf-8");
  let changed = false;

  // 1. Remove the service block.
  // Matches: blank line + "  {key}:\n" + all lines until (and including)
  // the next "      - unenter\n" (the service's network attachment).
  const serviceRegex = new RegExp(
    `\\n  ${key}:\\n` +
    `(?:(?!\\n  [a-zA-Z]).|\\n)*?` +
    `      - unenter\\n`,
    "s"
  );
  const withoutService = content.replace(serviceRegex, "\n");
  if (withoutService !== content) {
    content = withoutService;
    onLine(`� Removed service block "${key}" from docker-compose.yml`);
    changed = true;
  } else {
    onLine(`�a� Service block for "${key}" not found — skipping`);
  }

  // 2. Remove UPSTREAM_{KEY}: line from proxy environment (legacy cleanup).
  // Proxy v2 doesn't use these, but old docker-compose.yml may have them.
  const upstreamKey = `UPSTREAM_${key.toUpperCase()}`;
  const upstreamLine = new RegExp(`\\s*${upstreamKey}:\\s*"[^"]+"\\n`);
  const withoutUp = content.replace(upstreamLine, "");
  if (withoutUp !== content) {
    content = withoutUp;
    onLine(`� Removed ${upstreamKey} from proxy environment`);
    changed = true;
  }

  // 3. Remove depends_on entry from proxy service (legacy cleanup).
  const depsLine = new RegExp(`\\s*${key}:\\n\\s*condition: service_healthy\\n`);
  const withoutDeps = content.replace(depsLine, "");
  if (withoutDeps !== content) {
    content = withoutDeps;
    onLine(`� Removed "${key}" from proxy depends_on`);
    changed = true;
  }

  if (changed) {
    await writeFileAtomic(composePath, content);
  }
}
